fix Windows startup
manateelazycat/emacs-application-framework pull request #529
Opened 2021-01-22 03:29 UTC by xhcoding

2021-01-22 04:16 UTC, MatthewZMD commented
please rebase with latest commit

2021-01-22 04:27 UTC, xhcoding commented
是要把 3 个 commit rebase 成一个吗？

2021-01-22 05:40 UTC, wsw0108 commented
有个冲突，eaf-config-dir的

2021-01-22 06:21 UTC, xhcoding commented
好像 ok 了

2021-01-22 09:11 UTC, zsxh commented on eaf.py
> +        epc_log_dir = os.path.join(os.path.expanduser('~'), '.emacs.d', 'eaf');
I think epc_log_dir here should respect `eaf-config-location` variable.
这里不要把路径给写死了，还是跟 `eaf-config-location` 这个用户自定义变量保持一致吧

2021-01-22 09:14 UTC, zsxh commented on eaf.py
> +        epc_log_dir = os.path.join(os.path.expanduser('~'), '.emacs.d', 'eaf');
这个变量在 eaf.py 是 eaf_config_dir

2021-01-22 10:09 UTC, MatthewZMD requested changes

2021-01-22 10:09 UTC, MatthewZMD commented on eaf.py
> +            os.makedirs(epc_log_dir);
epc_log_dir等价于eaf_config_dir，不需要再创一个变量。正确做法是将eaf_config_dir调整为os.path.join

2021-01-22 10:45 UTC, xhcoding commented on eaf.py
> +            os.makedirs(epc_log_dir);
已经改了

2021-01-22 11:11 UTC, wsw0108 approved these changes

2021-01-22 11:49 UTC, merged

2021-01-22 11:50 UTC, manateelazycat commented
@xhcoding 

感谢补丁，Windows的用户应该怎么调用脚本呢？ 我们把调用方式更新到README中

2021-01-22 12:29 UTC, xhcoding commented
```
node install-eaf-win32.js
```

安装 npm 和 python 依赖包

2021-01-22 17:01 UTC, MatthewZMD commented
> ```
> node install-eaf-win32.js
> ```
> 
> 安装 npm 和 python 依赖包

下载这个需要windows管理员权限吗

2021-01-23 00:50 UTC, xhcoding commented
> > ```
> > node install-eaf-win32.js
> > ```
> > 
> > 
> > 安装 npm 和 python 依赖包
> 
> 下载这个需要windows管理员权限吗

不需要