Add the support for calling eaf on Windows from Emacs on WSL 1
manateelazycat/emacs-application-framework pull request #560
Opened 2021-02-02 04:11 UTC by yqu212

我实现了在emacs-china上面提到的[在wsl下面调用windows下eaf的想法](https://emacs-china.org/t/emacs-linux-windows/6199/1257)。

请各位指教。

2021-02-02 04:33 UTC, MatthewZMD commented on eaf.el
> +                   eaf-internal-process-prog eaf-internal-process-args)))
可以去掉if else直接`(let ((process-connection-type (not (eaf--called-from-wsl-on-windows-p)))`，如果区别只在这里的话

2021-02-02 04:33 UTC, MatthewZMD commented on eaf.el
> +  "Translate from a WSL path to a Windows path'"
`eaf--translate-wsl-url-to-windows`

2021-02-02 04:33 UTC, MatthewZMD commented on eaf.el
> +      (eaf--activate-emacs-linux-window))))
连环if建议用cond

2021-02-02 04:33 UTC, MatthewZMD commented on eaf.el
> +    (frame-parameter frame 'window-id)))
这两个得到的数值有多大区别？

2021-02-02 05:30 UTC, yqu212 commented on eaf.el
> +    (frame-parameter frame 'window-id)))
得到的数值不是一个概念。前者得到的是Windows的nwhd，后者得到的是Linux下的window id。eaf在Windows下运行，只认nwhd。

2021-02-02 06:03 UTC, manateelazycat commented
> 我实现了在emacs-china上面提到的[在wsl下面调用windows下eaf的想法](https://emacs-china.org/t/emacs-linux-windows/6199/1257)。
> 
> 请各位指教。
> 
> 目前使用起来还存在失焦的问题。主要体现在浏览器上面。pdf阅读器等app可以自动获取焦点。主要有两个问题：1. 浏览器刚打开的时候需要用alt-tab为emacs获取焦点；2. 打开一些网页不仅emacs没有获得焦点，还看不到eaf，需要改变一下window布局才会正常显示eaf。

现在论坛已经成功的是WSL2, 你这个方案是WSL?

2021-02-02 07:10 UTC, yqu212 commented
不不不，其实这个方案在wsl和wsl2上面应该都能行。这个方案依赖的是wsl和wsl2能够调直接用
windows程序的能力，而这个特性是两个版本wsl共有的，所以这个方案在两个版本的
wsl上应该都没有问题。

我只测试了wsl，也推荐大家在wsl上面使用eaf。在wsl2上面直接就可以用eaf，根本不需要
这样跨系统调用，只要配好声音支持就行了。只是wsl2跨系统文件访问性能低下、资源占
用大，根本就不好用，问题多多，比在虚拟机里面没好多少。没了跨系统文件访问特性，用
wsl2还不如用虚拟机。

虽然wsl底层实现不完整，但是它的跨系统文件访问用起来很不错。我这个方案可以有效利
用linux和windows上面的优势，最优化在windows系统上面使用emacs和eaf的体验。

2021-02-02 07:57 UTC, yqu212 commented
@MatthewZMD 已经改好。

2021-02-02 14:48 UTC, manateelazycat commented
> 不不不，其实这个方案在wsl和wsl2上面应该都能行。这个方案依赖的是wsl和wsl2能够调直接用
> windows程序的能力，而这个特性是两个版本wsl共有的，所以这个方案在两个版本的
> wsl上应该都没有问题。
> 
> 我只测试了wsl，也推荐大家在wsl上面使用eaf。在wsl2上面直接就可以用eaf，根本不需要
> 这样跨系统调用，只要配好声音支持就行了。只是wsl2跨系统文件访问性能低下、资源占
> 用大，根本就不好用，问题多多，比在虚拟机里面没好多少。没了跨系统文件访问特性，用
> wsl2还不如用虚拟机。
> 
> 虽然wsl底层实现不完整，但是它的跨系统文件访问用起来很不错。这个方案可以有效结
> 合linux和windows上面的优势，最优化在windows系统上面使用emacs和eaf的体验。

我的意思是，需不需要在代码级别区分WSL和WSL2 ? 还是可以一套代码支持WSL和WSL2？

2021-02-02 14:53 UTC, yqu212 commented
不需要。可以一套代码支持两种wsl。

2021-02-02 15:17 UTC, manateelazycat commented
EAF的启动流程是：
1. EAF Elisp代码
2. 启动EAF Python进程
3. Elisp端eaf-call 和 eaf-call-sync代码生效

建议你把get_emacs_xid和activate_emacs_wsl_window两个函数作为单独Python脚本，在Elisp端通过子进程方式来调用这些Python脚本。
这也可以避免EAF Python进程还没有启动完毕时调用 eaf-call 以及 eaf-call-sync 失效的问题，也许也是第一次启动浏览器没有获取焦点的原因（循环依赖）。

你本地尝试我的方法看看能否解决你最上面说的问题。

2021-02-02 15:19 UTC, manateelazycat commented
> 不需要。可以一套代码支持两种wsl。
> 
> 更新：刚才在wsl2下面验证了一下，似乎epc的网络地址需要转换一下才能行。现在epc默认听的是127.0.0.1，需要转换成windows的网络地址才行。wsl2和wsl 1在网络上面不一样，wsl2本质上是虚拟机，而wsl1是兼容层。所以前者的网络地址需要转换，后者就没有问题。这个问题我不想处理了。wsl2上面跨系统操作文件不好用，跨系统文件操作带来的负担也抵消了调用Windows下面的eaf带来的好处。

论坛里面的那些朋友应该是WSL2吧？ 如果cc

> 不需要。可以一套代码支持两种wsl。
> 
> 更新：刚才在wsl2下面验证了一下，似乎epc的网络地址需要转换一下才能行。现在epc默认听的是127.0.0.1，需要转换成windows的网络地址才行。wsl2和wsl 1在网络上面不一样，wsl2本质上是虚拟机，而wsl1是兼容层。所以前者的网络地址需要转换，后者就没有问题。这个问题我不想处理了。wsl2上面跨系统操作文件不好用，跨系统文件操作带来的负担也抵消了调用Windows下面的eaf带来的好处。

论坛那些朋友已经跑起来EAF了吧，epc应该没问题吧？

2021-02-02 15:28 UTC, yqu212 commented
> 建议你把get_emacs_xid和activate_emacs_wsl_window两个函数作为单独Python脚本，在Elisp端通过子进程方式来调用这些Python脚本。
这也可以避免EAF Python进程还没有启动完毕时调用 eaf-call 以及 eaf-call-sync 失效的问题，也许也是第一次启动浏览器没有获取焦点的原因（循环依赖）。

>你本地尝试我的方法看看能否解决你最上面说的问题。

之前实现的时候我就是采用这种方式，也有失焦的问题。为了提高性能我才把两个函数加到eaf.py里面的。

失焦的问题是windows上面都有的。我单独在windows下装了个emacs，一样有失焦的问题。

我觉得很奇怪，pdf就可以通过activate_emacs_window获取焦点，为什么browser就不行。不知道差别在哪儿？

> 论坛那些朋友已经跑起来EAF了吧，epc应该没问题吧？
他们是在wsl2内部跑当然不会有问题啊，只要听127.0.0.1就行了。可是跨了系统就是网络地址了，epc没有相应的转换肯定就会出问题。这个问题我觉得暂时不处理，等人提issue吧。毕竟在wsl2上面调windows上的eaf对一些人来说意义不大。他们既然选择wsl2，多半就已经放弃了跨系统文件访问。

2021-02-02 15:56 UTC, manateelazycat commented
> > 建议你把get_emacs_xid和activate_emacs_wsl_window两个函数作为单独Python脚本，在Elisp端通过子进程方式来调用这些Python脚本。
> > 这也可以避免EAF Python进程还没有启动完毕时调用 eaf-call 以及 eaf-call-sync 失效的问题，也许也是第一次启动浏览器没有获取焦点的原因（循环依赖）。
> 
> > 你本地尝试我的方法看看能否解决你最上面说的问题。
> 
> 之前实现的时候我就是采用这种方式，也有失焦的问题。为了提高性能我才把两个函数加到eaf.py里面的。
> 
> 失焦的问题是windows上面都有的。我单独在windows下装了个emacs，一样有失焦的问题。
> 
> 我觉得很奇怪，pdf就可以通过activate_emacs_window获取焦点，为什么browser就不行。不知道差别在哪儿？
> 
> > 论坛那些朋友已经跑起来EAF了吧，epc应该没问题吧？
> 
> 他们是在wsl2内部跑当然不会有问题啊，只要听127.0.0.1就行了。可是跨了系统就是网络地址了，epc没有相应的转换肯定就会出问题。这个问题我觉得暂时不处理，等人提issue吧。毕竟在wsl2上面调windows上的eaf对一些人来说意义不大。他们既然选择wsl2，多半就已经放弃了跨系统文件访问。现在这种跨系统调用的方案对他们来说有点多此一举。
> 
> 说到底这个方案只是一个过渡性方案，一旦微软发布了wsl2的gui支持，又改善了跨系统文件访问，这个方案就没有意义了。当然只要一个系统里面跑eaf更方便。

view.py 110 行有一个 print 语句，去掉注释后重启EAF, 每次Qt事件发生时，都会通过 eventFilter 这个函数在 ```*eaf*``` buffer 中打印具体的事件，可以对比一下PDF和浏览器应用的差别，说必定可以看到一些蛛丝马迹。

2021-02-02 15:57 UTC, yqu212 commented
好的。多谢。我去看看能不能解决问题。

2021-02-02 16:03 UTC, manateelazycat requested changes

2021-02-02 16:03 UTC, manateelazycat commented on eaf.py
> +import pygetwindow as gw
pygetwindow 的代码都要做Window平台判断，要不Linux平台会无法运行。

2021-02-02 16:05 UTC, manateelazycat commented on eaf.el
> +  (eaf-call-sync "activate_emacs_wsl_window" (frame-parameter nil 'name)))
如果这里是异步的 eaf-call-async 会不会更好？

2021-02-02 16:28 UTC, yqu212 commented on eaf.py
> +import pygetwindow as gw
已经修改。

2021-02-02 16:33 UTC, manateelazycat commented on eaf.py
> +import pygetwindow as gw
no，我的意思是把import搬到函数里，windows平台在函数里执行，别的平台就不执行 

要不函数那会报错

2021-02-02 16:37 UTC, yqu212 commented on eaf.el
> +  (eaf-call-sync "activate_emacs_wsl_window" (frame-parameter nil 'name)))
我看另外两个函数用的是同步的，我就也写成同步的。似乎没什么差别，那就先改成异步的吧。

2021-02-02 16:40 UTC, MatthewZMD commented on install-eaf-win32.js
> +    "pygetwindow"
可以把这个加到README吗

2021-02-02 16:51 UTC, MatthewZMD commented on eaf.el
> +                        url)
确认一下url不是一个web链接

2021-02-02 16:51 UTC, yqu212 commented on eaf.py
> +import pygetwindow as gw
我没有把import加到函数里面，只是让函数在非windows平台为空。

我觉得这样会性能上好一点，之前改为加在eaf.py里面就是为了不每次调用都import一遍。（我想多了？）

2021-02-02 17:04 UTC, yqu212 commented on install-eaf-win32.js
> +    "pygetwindow"
已经加到Dependency List

2021-02-02 17:05 UTC, yqu212 commented on eaf.el
> +                        url)
哦。这个不用担心。我写的时候注意了，如果是web链接会原样输出。

2021-02-02 17:09 UTC, MatthewZMD commented
Rebase一下最新的代码

2021-02-02 18:00 UTC, yqu212 commented
抱歉，第一次rebase upstream，学到了。

2021-02-02 20:17 UTC, manateelazycat commented on eaf.py
> +import pygetwindow as gw
我不知道windows性能咋样，其实每次import很快，甚至每次都子进程都可以

2021-02-02 20:18 UTC, manateelazycat commented on eaf.py
> +import pygetwindow as gw
else pass 去掉吧，没必要

2021-02-02 20:20 UTC, manateelazycat commented
> > > 建议你把get_emacs_xid和activate_emacs_wsl_window两个函数作为单独Python脚本，在Elisp端通过子进程方式来调用这些Python脚本。
> > > 这也可以避免EAF Python进程还没有启动完毕时调用 eaf-call 以及 eaf-call-sync 失效的问题，也许也是第一次启动浏览器没有获取焦点的原因（循环依赖）。
> > 
> > 
> > > 你本地尝试我的方法看看能否解决你最上面说的问题。
> > 
> > 
> > 之前实现的时候我就是采用这种方式，也有失焦的问题。为了提高性能我才把两个函数加到eaf.py里面的。
> > 失焦的问题是windows上面都有的。我单独在windows下装了个emacs，一样有失焦的问题。
> > 我觉得很奇怪，pdf就可以通过activate_emacs_window获取焦点，为什么browser就不行。不知道差别在哪儿？
> > > 论坛那些朋友已经跑起来EAF了吧，epc应该没问题吧？
> > 
> > 
> > 他们是在wsl2内部跑当然不会有问题啊，只要听127.0.0.1就行了。可是跨了系统就是网络地址了，epc没有相应的转换肯定就会出问题。这个问题我觉得暂时不处理，等人提issue吧。毕竟在wsl2上面调windows上的eaf对一些人来说意义不大。他们既然选择wsl2，多半就已经放弃了跨系统文件访问。现在这种跨系统调用的方案对他们来说有点多此一举。
> > 说到底这个方案只是一个过渡性方案，一旦微软发布了wsl2的gui支持，又改善了跨系统文件访问，这个方案就没有意义了。当然只要一个系统里面跑eaf更方便。
> 
> view.py 110 行有一个 print 语句，去掉注释后重启EAF, 每次Qt事件发生时，都会通过 eventFilter 这个函数在 `*eaf*` buffer 中打印具体的事件，可以对比一下PDF和浏览器应用的差别，说必定可以看到一些蛛丝马迹。

事件上有区别吗？

2021-02-03 07:07 UTC, xhcoding commented
刚打开失焦可以考虑在 reparent  后激活一下 emacs 窗口

2021-02-03 08:48 UTC, yqu212 commented on eaf.py
> +import pygetwindow as gw
已经去掉了。

2021-02-03 10:02 UTC, manateelazycat commented
> 刚打开失焦可以考虑在 reparent 后激活一下 emacs 窗口

@yqu212 尝试一下，看看有没有用？

2021-02-03 14:48 UTC, yqu212 commented
> > > > 建议你把get_emacs_xid和activate_emacs_wsl_window两个函数作为单独Python脚本，在Elisp端通过子进程方式来调用这些Python脚本。
> > > > 这也可以避免EAF Python进程还没有启动完毕时调用 eaf-call 以及 eaf-call-sync 失效的问题，也许也是第一次启动浏览器没有获取焦点的原因（循环依赖）。
> > > 
> > > 
> > > > 你本地尝试我的方法看看能否解决你最上面说的问题。
> > > 
> > > 
> > > 之前实现的时候我就是采用这种方式，也有失焦的问题。为了提高性能我才把两个函数加到eaf.py里面的。
> > > 失焦的问题是windows上面都有的。我单独在windows下装了个emacs，一样有失焦的问题。
> > > 我觉得很奇怪，pdf就可以通过activate_emacs_window获取焦点，为什么browser就不行。不知道差别在哪儿？
> > > > 论坛那些朋友已经跑起来EAF了吧，epc应该没问题吧？
> > > 
> > > 
> > > 他们是在wsl2内部跑当然不会有问题啊，只要听127.0.0.1就行了。可是跨了系统就是网络地址了，epc没有相应的转换肯定就会出问题。这个问题我觉得暂时不处理，等人提issue吧。毕竟在wsl2上面调windows上的eaf对一些人来说意义不大。他们既然选择wsl2，多半就已经放弃了跨系统文件访问。现在这种跨系统调用的方案对他们来说有点多此一举。
> > > 说到底这个方案只是一个过渡性方案，一旦微软发布了wsl2的gui支持，又改善了跨系统文件访问，这个方案就没有意义了。当然只要一个系统里面跑eaf更方便。
> > 
> > 
> > view.py 110 行有一个 print 语句，去掉注释后重启EAF, 每次Qt事件发生时，都会通过 eventFilter 这个函数在 `*eaf*` buffer 中打印具体的事件，可以对比一下PDF和浏览器应用的差别，说必定可以看到一些蛛丝马迹。
> 
> 事件上有区别吗？

事件上有区别。

pdf的事件是

> 1612363538.3970635 68
> 1612363538.3970635 68
> 1612363538.4127169 13

而浏览器没有这个事件，不过它总是报这个错
>QObject::killTimer: Timers cannot be stopped from another thread
>QObject::~QObject: Timers cannot be stopped from another thread

2021-02-03 14:57 UTC, yqu212 commented
> > 刚打开失焦可以考虑在 reparent 后激活一下 emacs 窗口
> 
> @yqu212 尝试一下，看看有没有用？

@manateelazycat  @xhcoding 我在view.py的showEvent里面加了激活emacs window的代码，有效果，浏览器打开就正常了。

>     def showEvent(self, event):
>         # NOTE: we must reparent after widget show, otherwise reparent operation maybe failed.
>         self.reparent()
>         self.buffer.eval_in_emacs.emit('eaf-activate-emacs-window', [])

不过，在浏览器里面打开链接的时候还是会失焦。有两种情况：

1. 在当前页面打开链接。会失焦，但可以看见网页。
2. 在新标签页打开链接。不仅会失焦，而且看不到网页内容，需要改变窗口布局才能看到网页内容。

2021-02-04 10:56 UTC, yqu212 commented
上面提到两种失焦已经解决。我在Windows上专门测试了一下，windows上面的emacs打开eaf
browser已经不存在失焦问题了。

现在还有最后一个问题：使用eaf-open-browser-with-history连续打开新的网页，第
一个网页一切正常，从第二个开始就不能立刻看到网页，需要switch-buffer或者改变一下
窗口布局才行。eaf是正常运行着的，只是reparent的时候出了什么错。我还没找到原因。
这个问题只出现在wsl下emacs调用windows下eaf时才会出现，windows下使用emacs没有看到这个问题。

2021-02-04 17:12 UTC, manateelazycat commented
> 上面提到两种失焦已经解决 。我在Windows上专门测试了一下，windows上面的emacs打开eaf
> browser已经不存在失焦问题了。
> 
> 现在还有最后一个问题：使用eaf-open-browser-with-history连续打开新的网页，第
> 一个网页一切正常，从第二个开始就不能立刻看到网页，需要switch-buffer或者改变一下
> 窗口布局才行。eaf是正常运行着的，只是reparent的时候出了什么错。我还没找到原因。
> 这个问题只在wsl下emacs调用windows下eaf时才会出现，windows下使用emacs没有看到这个问题。

小问题，linux也有，换ipc后遗症。
补丁我明天看一下，没问题就合并

2021-02-04 17:19 UTC, yqu212 commented
合并之前需不需要我压缩成一个commit？

2021-02-04 17:21 UTC, MatthewZMD commented
> > 上面提到两种失焦已经解决 。我在Windows上专门测试了一下，windows上面的emacs打开eaf
> > browser已经不存在失焦问题了。
> > 现在还有最后一个问题：使用eaf-open-browser-with-history连续打开新的网页，第
> > 一个网页一切正常，从第二个开始就不能立刻看到网页，需要switch-buffer或者改变一下
> > 窗口布局才行。eaf是正常运行着的，只是reparent的时候出了什么错。我还没找到原因。
> > 这个问题只在wsl下emacs调用windows下eaf时才会出现，windows下使用emacs没有看到这个问题。
> 
> 小问题，linux也有，换ipc后遗症。
> 补丁我明天看一下，没问题就合并

我似乎没遇到过这个问题。


> 合并之前需不需要我压缩成一个commit？

不用

2021-02-04 23:06 UTC, merged

2021-02-04 23:07 UTC, MatthewZMD commented
感谢补丁。你不需要压缩成一个，我们这边可以Squash and Merge

2021-02-04 23:10 UTC, yqu212 commented
我还是压缩了，最后三个commit